### ISSUE TITLE
Pool release connection do not drop open transactions.

### ISSUE THREAD

**Issue by tonal** [aio-libs/aiomysql#679] opened 2022-01-21 08:08 UTC
### Describe the bug

Pool release connection do not drop open transactions.
Need invoke [mysql_reset_connection](https://dev.mysql.com/doc/c-api/8.0/en/mysql-reset-connection.html)()

### To Reproduce

```python
  async with aiomysql.create_pool(
    autocommit=False,
  ) as pool: # type: aiomysql.pool.Pool
    async with pool.acquire() as conn:
      async with conn.cursor() as curs: # type: aiomysql.cursors.Cursor
        await curs.execute('UPDATE table1 SET id=1 where id=1') # ! Some DML statement start RW transaction
        rc = await curs.execute('SELECT * FROM information_schema.innodb_trx')
        assert rc > 0
        print(1, rc)
        if rc:
          print(curs.description)
        async for row in curs:
          print(row)

    async with pool.acquire() as conn:
      async with conn.cursor() as curs: # type: aiomysql.cursors.Cursor
        rc = await curs.execute('SELECT * FROM information_schema.innodb_trx')
        print(2, rc)
        assert rc == 0 # !!! Bat you see transaction starts prev DML
        async for row in curs:
          print(row)
```

### Expected behavior

Rolls back any active transactions.

### Logs/tracebacks

```python-traceback
1 1
(('trx_id', 8, None, 21, 21, 0, False), ('trx_state', 253, None, 13, 13, 0, False), ('trx_started', 12, None, 19, 19, 0, False), ('trx_requested_lock_id', 253, None, 105, 105, 0, True), ('trx_wait_started', 12, None, 19, 19, 0, True), ('trx_weight', 8, None, 21, 21, 0, False), ('trx_mysql_thread_id', 8, None, 21, 21, 0, False), ('trx_query', 253, None, 1024, 1024, 0, True), ('trx_operation_state', 253, None, 64, 64, 0, True), ('trx_tables_in_use', 8, None, 21, 21, 0, False), ('trx_tables_locked', 8, None, 21, 21, 0, False), ('trx_lock_structs', 8, None, 21, 21, 0, False), ('trx_lock_memory_bytes', 8, None, 21, 21, 0, False), ('trx_rows_locked', 8, None, 21, 21, 0, False), ('trx_rows_modified', 8, None, 21, 21, 0, False), ('trx_concurrency_tickets', 8, None, 21, 21, 0, False), ('trx_isolation_level', 253, None, 16, 16, 0, False), ('trx_unique_checks', 3, None, 1, 1, 0, False), ('trx_foreign_key_checks', 3, None, 1, 1, 0, False), ('trx_last_foreign_key_error', 253, None, 256, 256, 0, True), ('trx_adaptive_hash_latched', 3, None, 1, 1, 0, False), ('trx_adaptive_hash_timeout', 8, None, 21, 21, 0, False), ('trx_is_read_only', 3, None, 1, 1, 0, False), ('trx_autocommit_non_locking', 3, None, 1, 1, 0, False), ('trx_schedule_weight', 8, None, 21, 21, 0, True))
(21824227, 'RUNNING', datetime.datetime(2022, 1, 21, 7, 45, 14), None, None, 2, 44, 'SELECT * FROM information_schema.innodb_trx', None, 0, 1, 2, 1136, 1, 0, 0, 'REPEATABLE READ', 1, 1, None, 0, 0, 0, 0, None)
2 1
(21824227, 'RUNNING', datetime.datetime(2022, 1, 21, 7, 45, 14), None, None, 2, 44, 'SELECT * FROM information_schema.innodb_trx', None, 0, 1, 2, 1136, 1, 0, 0, 'REPEATABLE READ', 1, 1, None, 0, 0, 0, 0, None)
```

### Python Version

```console
$ python --version
3.10.1
```

### aiomysql Version

```console
$ python -m pip show aiomysql
Name: aiomysql
Version: 0.0.22
Summary: MySQL driver for asyncio.
Home-page: https://github.com/aio-libs/aiomysql
Author: Nikolay Novik
Author-email: nickolainovik@gmail.com
License: MIT
Location: /home/tonal/.pyenv/versions/3.10.1/envs/epool-delivery_calc/lib/python3.10/site-packages
Requires: PyMySQL
Required-by:
```

### PyMySQL Version

```console
$ python -m pip show PyMySQL
Name: PyMySQL
Version: 0.9.3
Summary: Pure Python MySQL Driver
Home-page: https://github.com/PyMySQL/PyMySQL/
Author: yutaka.matsubara
Author-email: yutaka.matsubara@gmail.com
License: "MIT"
Location: /home/tonal/.pyenv/versions/3.10.1/envs/epool-delivery_calc/lib/python3.10/site-packages
Requires: 
Required-by: aiomysql
```

### SQLAlchemy Version

```console
$ python -m pip show sqlalchemy
```

### OS

$ lsb_release -a
LSB Version:    core-11.1.0ubuntu2-noarch:desktop-3.1-amd64:desktop-3.1-noarch:desktop-3.2-amd64:desktop-3.2-noarch:desktop-4.0-amd64:desktop-4.0-noarch:desktop-4.1-amd64:desktop-4.1-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.0-amd64:graphics-3.0-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch:graphics-4.1-amd64:graphics-4.1-noarch:multimedia-3.2-amd64:multimedia-3.2-noarch:multimedia-4.0-amd64:multimedia-4.0-noarch:multimedia-4.1-amd64:multimedia-4.1-noarch:qt4-3.1-amd64:qt4-3.1-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Neon
Description:    KDE neon User - Plasma 25th Anniversary Edition
Release:        20.04
Codename:       focal

### Database type and version

```console
SELECT VERSION();
8.0.21
```

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Nothing4You** [comment] 2022-07-10 22:40
functionality wise this is a duplicate of #462, please refer to that issue instead.

**Closed by Nothing4You** 2022-07-10 22:40 UTC
Labels: bug
