### ISSUE TITLE
the sqlalchemy demo is broken with python 3.7

### ISSUE THREAD

**Issue by MarkWh1te** [aio-libs/aiomysql#317] opened 2018-07-13 03:22 UTC
```Python
        async for row in conn.execute(tbl.select()):
            print(row.id, row.val)
```
the sqlalchemy demo is broken with python 3.7
```
TypeError: 'async for' received an object from __aiter__ that does not implement __anext__: coroutine
```

**Comment by asvetlov** [comment] 2018-07-13 08:22
@MarkWh1te sorry, your fix is incorrect.
The proper fix should drop `async` from `def __aiter__` in `cursor.py`

**Comment by sc-syf** [comment] 2018-09-14 06:33
yeah, just as @asvetlov note,   with python 3.7, you should change `async def __aiter__` to `def __aiter__`

**Comment by dnp1** [comment] 2018-09-25 22:05
@MarkWh1te 

If you yield values from an "async function", an AsyncGenerator is returned and everything is fine for python 3.7

But here you intend to return an object that already implements `__anext__` (`self`), so you must drop the `async` from `__aiter__` as pointed above.  


I'm waiting for this fix, also. Are you planning to complete it or I should open my pull request?

**Comment by sonliviy** [comment] 2019-01-23 14:20
Hey, i have the same issue. I think need to fix this line too.
https://github.com/aio-libs/aiomysql/blob/66d8657d5a415b357003ef67c6b31a3ae6e3167f/aiomysql/utils.py#L73

**Closed** 2019-05-22 09:47 UTC
Labels: pr-available

**Comment by stkrp** [comment] 2019-12-17 16:00
Hello.

I'm facing with same problem on version 0.0.20 from `master` branch (not PyPI). Could the following code be the cause? I use Python 3.8 in Docker.

```python
class _SAConnectionContextManager(_ContextManager):
    async def __aiter__(self):
        result = await self._coro
        return result
```
https://github.com/stkrp/aiomysql/blob/b16e5bd8f31e0644d180599c87deb9ffea0c2007/aiomysql/utils.py#L73
