### ISSUE TITLE
SSCursor can't close while raise Error

### ISSUE THREAD

**Issue by ppd0705** [aio-libs/aiomysql#428] opened 2019-08-15 10:20 UTC
if server send a error to SSCurosr, SSCursor try to call self._result._finish_unbuffered_query  in close function
```python
# SSCursor close funcion in  cursor.py line 604
if self._result is not None and self._result is conn._result:
    await self._result._finish_unbuffered_query()
````
but there is not a byte to read  after recived a error packge, so the loop is allways waiting in the time, the error could't raise out .
```python
# _finish_unbuffered_query function in connection.py line 1197  
while self.unbuffered_active:
    packet = await self.connection._read_packet()
```

I met the bug after I seted a mysql variable 
```shell
SET GLOBAL MAX_EXECUTION_TIME=3000
```
a  SELECT statement will be aborted if it takes more than 3s.   

the connection received a error package with erorno 3024, but the loop is waiting  packge to finitshed  unbuffered_query

**Comment by ppd0705** [comment] 2019-08-16 13:24
Can someone respond to me?

**Comment by terrycain** [comment] 2019-08-16 17:13
Can you post a reproducible test case

**Comment by ppd0705** [comment] 2019-08-17 05:15
you can reproduce this by 2 steps:

1. set  MAX_EXECUTION_TIME for the Mysql server
2. select a large data that spend time more than the MAX_EXECUTION_TIME, use SScursor in WITH statement, simple code like
```python
async with conn.cursor(SScursor) as cursor:
    await cursor.execute("SELECT a large data")
    await ret = cursor.fetchall()
```

the conn received a error package with errorno 3024 and msg "Query execution was interrupted, maximum statement execution time exceeded ".
before raise error, the cursor.close() is called because the WITH statement.
then coon is waiting a EOF package to finish unbuffed query, but mysql server do not need a to send EOF package in this satuation.

**Comment by ppd0705** [comment] 2019-09-15 15:54
I fixed the issue for pymysql in the [commit](https://github.com/PyMySQL/PyMySQL/commit/f8c31d40c5abda9e03de5df34ea692b428fb6677)

**Comment by KOR-Believer** [comment] 2021-12-21 05:01
Hello @ppd0705.
I also faced the same problem.

```sql
SELECT /*+ MAX_EXECUTION_TIME(3000) */ col1, col2 FROM table #some heavy query
```

If aiomysql updates the pymysql version to 0.10.0 or higher, will the problem be solved?

If the aiomysql does not update, is there any other alternative?

**Comment by ppd0705** [comment] 2021-12-21 05:39
this bug can only be fixed in aiomysql and has nothing to do with the version of pymysql

**Comment by Nothing4You** [comment] 2022-02-03 18:16
As I'm working on creating test cases for this I don't believe this is resolved yet, not resolved in PyMySQL either.

On aiomysql without the patch from #646 the connection gets stuck, which matches the original report of this issue by @ppd0705.

With #646 applied I'm seeing the same behavior as in PyMySQL, which I believe is still wrong:

The initial query succeeds, even though it should result in a timeout.
After this query, when issuing another query, I'm receiving the unrelated OperationalError 3024, which should have been raised for the previous `execute()`.

```py3
connection = pymysql.connect(
    host='127.0.0.1',
    port=3306,
    db='mysql',
    charset='utf8mb4',
    user='root',
)

with connection.cursor(cursor=pymysql.cursors.SSCursor) as cur:
    cur.execute("DROP TABLE IF EXISTS tbl;")

    cur.execute("""
        CREATE TABLE tbl (
        id MEDIUMINT NOT NULL AUTO_INCREMENT,
        name VARCHAR(255) NOT NULL,
        PRIMARY KEY (id));
        """)

    for i in [(1, 'a'), (2, 'b'), (3, 'c')]:
        cur.execute("INSERT INTO tbl VALUES(%s, %s)", i)

    connection.commit()

    cur.execute("SELECT /*+ MAX_EXECUTION_TIME(2000) */ *,sleep(0.1) FROM tbl")
    r = cur.fetchone()

    assert r is not None

    print("retrieved data within long timeout:")
    print(repr(r))

    cur.execute("SELECT 1")
    (r,) = cur.fetchone()

    assert r == 1

    print("selected 1")

    cur.execute("SELECT /*+ MAX_EXECUTION_TIME(1) */ *,sleep(0.1) FROM tbl")
    r = cur.fetchone()

    assert r is not None

    print("retrieved data within short timeout:")
    print(repr(r))

    cur.execute("SELECT 1")
    (r,) = cur.fetchone()

    assert r == 1

    print("selected 1")
```

```pytb
retrieved data within long timeout:
(1, 'a', 0)
.../PyMySQL/pymysql/connections.py:803: UserWarning: Previous unbuffered result was left incomplete
  warnings.warn("Previous unbuffered result was left incomplete")
selected 1
retrieved data within short timeout:
(1, 'a', 1)
Traceback (most recent call last):
  File ".../PyMySQL/pmtest.py", line 52, in <module>
    cur.execute("SELECT 1")
  File ".../PyMySQL/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File ".../PyMySQL/pymysql/cursors.py", line 429, in _query
    conn.query(q, unbuffered=True)
  File ".../PyMySQL/pymysql/connections.py", line 548, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File ".../PyMySQL/pymysql/connections.py", line 804, in _execute_command
    self._result._finish_unbuffered_query()
  File ".../PyMySQL/pymysql/connections.py", line 1265, in _finish_unbuffered_query
    packet = self.connection._read_packet()
  File ".../PyMySQL/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File ".../PyMySQL/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File ".../PyMySQL/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (3024, 'Query execution was interrupted, maximum statement execution time exceeded')
```

I wouldn't expect this to fail on `select 1`.

**Comment by KOR-Believer** [comment] 2022-02-04 02:49
MAX_EXECUTION_TIME issues cannot be simulated with SLEEP().
You need an actual slow query.
That's why I couldn't write a test case.

**Comment by Nothing4You** [comment] 2022-02-04 11:36
they actually can, you need to carefully craft the queries though.

example (mysql 8.0):
```
mysql> SELECT /*+ MAX_EXECUTION_TIME(1) */ data, sleep(1) FROM test;
ERROR 3024 (HY000): Query execution was interrupted, maximum statement execution time exceeded
```

from [mysql 8.0 docs|https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_sleep] about `SLEEP()`:
> When [SLEEP()](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_sleep) is the only thing invoked by a query that is interrupted, it returns 1 and the query itself returns no error.

> When [SLEEP()](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_sleep) is only part of a query that is interrupted, the query returns an error

the key takeaway is that sleep cannot be the only part of the query.

see for example https://github.com/Nothing4You/PyMySQL/blob/8c373feb9036b4c19eb338220f47586f26e5afd0/pymysql/tests/test_cursor.py#L137

**Comment by Nothing4You** [comment] 2022-02-04 11:37
this is also similar to how MySQL implements this in their own tests: https://github.com/mysql/mysql-server/blob/mysql-8.0.28/mysql-test/t/max_statement_time.test

**Comment by Nothing4You** [comment] 2022-02-05 00:53
definitely fun to test, in some cases I can even get PyMySQL to raise a ProgrammingError from `SELECT /*+ MAX_EXECUTION_TIME(1) */ *,sleep(1) FROM tbl WHERE name='a'`, with a low chance though, i suspect related to whther the query is cached on MySQL side.

**Comment by Nothing4You** [comment] 2022-02-05 01:09
continuing in https://github.com/PyMySQL/PyMySQL/issues/1032

**Comment by Nothing4You** [comment] 2022-02-06 04:36
tests for PyMySQL have been built, see https://github.com/PyMySQL/PyMySQL/pull/1033

**Comment by Nothing4You** [comment] 2022-02-06 05:44
(failing) tests can be seen in https://github.com/Nothing4You/aiomysql/actions/runs/1801465357
as I haven't bothered with implementing some sort of per test timeout yet this currently effectively only shows the process hanging at some point.

test cases are added in #728

**Comment by Nothing4You** [comment] 2022-02-06 06:54
reopening for the missing test case for https://github.com/aio-libs/aiomysql/issues/428#issuecomment-1029268485

**Comment by Nothing4You** [comment] 2022-02-06 07:51
as described in https://github.com/PyMySQL/PyMySQL/issues/1032#issuecomment-1030764742 onwards I don't think it's realistic to write a test case for this specific issue due to lack of determinism.

I believe https://github.com/PyMySQL/PyMySQL/pull/1035/commits/0c6e5811da9a19d1ab757d07fe2a368606b5fbee should be the final fix needed to resolve this.

**Comment by Nothing4You** [comment] 2022-02-08 10:29
https://github.com/PyMySQL/PyMySQL/pull/1035 isn't ported yet - once I've done that I'll close this.

**Closed** 2022-04-11 00:09 UTC
Labels: bug
