### ISSUE TITLE
SQL Execution Creates Implicit Transaction without Rollback.

### ISSUE THREAD

**Issue by seandstewart** [aio-libs/aiomysql#562] opened 2021-01-26 18:12 UTC
Hello - 

First of all, I want to thank you all for your work maintaining this library.

I'm currently using this library to support some read-only requirements in an application.

Unfortunately, this library implicitly begins transactions, but fails to roll them back when a connection is released back into a connection pool. The problem with this implementation is that even a read-only client needs to be aware of these transactions and choose to either 1) set autocommit, or 2) explicitly rollback after every query.

The aside from the risk of getting increasingly stale data the longer an application runs, this also locks any table accessed within that transaction from access for operations which may change the shape of the table (i.e., adding an index or column). If an alter is attempted on a table with a Read Metadata lock (which transactions acquire), that alter will hang indefinitely and also prevent any subsequent operations on the table in question.

In my experience with other libraries, if a transaction block is begun but not committed, the library will automatically emit a rollback. This can be handled one of two ways:

1. The library requires an explicit transaction context (when not in autocommit mode). When used as a context manager, the library can automatically emit a commit/rollback when exiting the context. (This is how asyncpg has implemented [transactions](https://magicstack.github.io/asyncpg/current/api/index.html#transactions)).
2. The library has an implicit transaction for every connection. It should also have an implicit rollback when that connection is released back to the connection pool (when not in autocommit mode).

A sample of the code which I'm using:

The Connector class:

```python
import aiomysql

from app import settings


class MySQLConnector:
    """A simple connector for aiomysql."""

    __slots__ = ("pool",)

    def __init__(self, *, pool: aiomysql.Pool = None):
        self.pool: aiomysql.Pool = pool

    def __repr__(self):
        open = self.pool is not None
        return f"<{self.__class__.__name__} {open=}>"

    async def initialize(self):
        if not self.pool:
            self.pool = await create_pool()

    @contextlib.asynccontextmanager
    async def connection(self, *, c: aiomysql.Connection = None) -> aiomysql.Connection:
        if c:
            yield c
        else:
            async with self.pool.acquire() as conn:
                yield conn

    async def close(self, timeout: int = 10):
        if self.pool:
            self.pool.close()
            await asyncio.wait_for(self.pool.wait_closed(), timeout=timeout)
            self.pool = None

    def __del__(self):
        if not asyncio:  # Python is shutting down.
            return
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                loop.create_task(self.close())
            else:
                loop.run_until_complete(self.close())
        except RuntimeError:
            pass


async def create_pool():
    return await aiomysql.create_pool(
        user=settings.user,
        password=settings.password,
        host=settings.host,
        db=settings.db,
        cursorclass=DictCursor,
        maxsize=200,
    )
```

A sample query client:

```python
class QueryClient:
    __slots__ = ("connector",)

    def __init__(self, *, c: MySQLConnector = None):
        self.connector = c or MySQLConnector()

    async def get_the_answer(
        self, *, c: aiomysql.Connection = None
    ) -> Literal[42]:
        async with self.connector.connection() as c:
            async with c.cursor() as cur:
                await cur.execute("SELECT answer FROM everything;")
                (answer,) = await cur.fetchone()
        return answer
```

Reproduce the locked state by:

1. Execute QueryClient.get_the_answer() 
2. In a separate connection, run an `ALTER` on the table (any will do).

The alter will hang indefinitely. At this point, even disconnecting the client which ran the `ALTER` will leave the query pending server side and block any other access attempts on the table. The only mitigation is to close all connections by the first client, or manually delete the pending queries in MySQL.

You can verify that there is an active transaction held by the first client by running the following commands and cross-referencing thread IDs in the process list with thread IDs listed as active under the `Transactions` section of the engine status.

```sql
SHOW FULL PROCESSLIST;
SHOW ENGINE InnoDB STATUS;
```

Now, this can be mitigated by either running in autocommit mode or explicitly rolling back after every query, but I do think both options are less than ideal and are prone to individuals entering the state which I described above.

**Comment by Nothing4You** [comment] 2022-07-11 01:00
this is a duplicate of #462, please refer to that issue instead.

**Closed by Nothing4You** 2022-07-11 01:00 UTC
Labels: enhancement
